[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://electrostar2024-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
